### ISSUE TITLE
Undefined index: randomaffiliates

### ISSUE THREAD

**Issue by aurenen** [Lysianthus/enthusiast#1]
There's a notice for fanlisting collectives if you have full error reporting turned on.

```Notice: Undefined index: randomaffiliates in /home/[redacted path]/mod_owned.php on line 2000```

I haven't had time to look at it myself since I was just helping someone install the new version, but I think it's with a typo in the array index name? Should it be 'randomaffiliate' instead?

```$stats['randomaffiliates'] .= '">' . $randaff['title'] . '</a> ';```

Thanks!

**Comment by Lysianthus** [comment]
It was definitely a typo. It appears that it's in the original version as well. It should be fixed now. Commit: 5219bf5c1ad2c88215eec6c980fa7974351c9051

Thank you for pointing it out!
