### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by christineknight** [Lysianthus/enthusiast#3]
Hello, I am not sure if you still provide support, but hopefully someone can help me. After I fill in all the info to create my collective at /install.php, I receive this error:

_Error executing query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'affiliates' already exists; CREATE TABLE `affiliates` (`affiliateid` int(5) NOT NULL auto_increment,`url` varchar(254) NOT NULL default '',`title` varchar(254) NOT NULL default '',`imagefile` varchar(254) default NULL,`email` varchar(255) NOT NULL default '',`added` date default NULL,PRIMARY KEY (`affiliateid`)) ENGINE=MyISAM AUTO_INCREMENT=1_

Thank you kindly.

**Comment by Lysianthus** [comment]
Hello!

Is this a fresh install? The error says there is already the table `affiliates` in the database. Have you tried dropping the tables in the database? If this is a fresh install, the database should be completely empty.

**Comment by christineknight** [comment]
Hi! I'm so happy you responded.
Ok, so I'm a bit of a noob and had some issues setting up the correct config.php file, so I probably accidentally created those tables. I've since dropped them, but when I tried installing again I received this error:

_Error executing query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes; CREATE TABLE `settings` (`setting` varchar(255) NOT NULL default '',`title` varchar(255) NOT NULL default '',`value` text NOT NULL,`help` text NOT NULL,PRIMARY KEY (`setting`)) ENGINE=MyISAM_

Edit: Also yes, fresh install. In case this is helpful, I am using PHP 7.4 and MySQL 8 (my host only offers 8, in the process of trying to find a host that offers <8)

**Comment by Lysianthus** [comment]
Unfortunately, this version of Enthusiast does not support MySQL 8. I recommend that you check out this alternate version [gitlab.com/tfl-php-scripts/enthusiast](https://gitlab.com/tfl-php-scripts/enthusiast) and see if it works in your environment.

**Comment by christineknight** [comment]
Thank you for your help, however I unfortunately receive the same error using that version of the script. I appreciate your time.

**Comment by Lysianthus** [comment]
No problem!
